version: '2'
services:
  postgres:
    build: devop/db_app_Bluemix
  redis:
    image: redis
  web:
    build: .
    command: python betasmartz/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/betasmartz
    ports:
      - "80:8000"
    links:
      - postgres:postgres
      - redis:redis
    depends_on:
      - postgres
      - redis
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - ENVIRONMENT=local
      - REDIS_URI=redis://localhost:6379