SUCCESS_MESSAGE = "Your application has been submitted successfully, " \
                  "you will receive a confirmation email" \
                  " following a BetaSmartz approval."
INVITATION_PENDING = 0
INVITATION_SUBMITTED = 1
INVITATION_ACTIVE = 3
INVITATION_CLOSED = 4
EMAIL_INVITATION_STATUSES = (
    (INVITATION_PENDING, 'Pending'), (INVITATION_SUBMITTED, 'Submitted'),
    (INVITATION_ACTIVE, 'Active'), (INVITATION_CLOSED, 'Closed'))
EMPLOYMENT_STATUS_FULL_TIME = 0
EMPLOYMENT_STATUS_PART_TIME = 1
EMPLOYMENT_STATUS_SELF_EMPLOYED = 2
EMPLOYMENT_STATUS_STUDENT = 3
EMPLOYMENT_STATUS_RETIRED = 4
EMPLOYMENT_STATUS_HOMEMAKER = 5
EMPLOYMENT_STATUS_UNEMPLOYED = 6
EMPLOYMENT_STATUSES = (
    (EMPLOYMENT_STATUS_FULL_TIME, 'Employed (full-time)'),
    (EMPLOYMENT_STATUS_PART_TIME, 'Employed (part-time)'),
    (EMPLOYMENT_STATUS_SELF_EMPLOYED, 'Self-employed'),
    (EMPLOYMENT_STATUS_STUDENT, 'Student'),
    (EMPLOYMENT_STATUS_RETIRED, 'Retired'),
    (EMPLOYMENT_STATUS_HOMEMAKER, 'Homemaker'),
    (EMPLOYMENT_STATUS_UNEMPLOYED, "Not employed"),
)
INVITATION_ADVISOR = 0
AUTHORIZED_REPRESENTATIVE = 1
INVITATION_SUPERVISOR = 2
INVITATION_CLIENT = 3
INVITATION_TYPE_CHOICES = (
    (INVITATION_ADVISOR, "Advisor"),
    (AUTHORIZED_REPRESENTATIVE, 'Authorised representative'),
    (INVITATION_SUPERVISOR, 'Supervisor'),
    (INVITATION_CLIENT, 'Client'),
)
INVITATION_TYPE_DICT = {
    str(INVITATION_ADVISOR): "advisor",
    str(AUTHORIZED_REPRESENTATIVE): "authorised_representative",
    str(INVITATION_CLIENT): "client",
    str(INVITATION_SUPERVISOR): "supervisor"
}
TFN_YES = 0
TFN_NON_RESIDENT = 1
TFN_CLAIM = 2
TFN_DONT_WANT = 3
TFN_CHOICES = (
    (TFN_YES, "Yes"),
    (TFN_NON_RESIDENT, "I am a non-resident of Australia"),
    (TFN_CLAIM, "I want to claim an exemption"),
    (TFN_DONT_WANT, "I do not want to quote a Tax File Number or exemption"),)
PERSONAL_DATA_FIELDS = ('date_of_birth', 'gender', 'phone_num')
ASSET_FEE_EVENTS = ((0, 'Day End'),
                    (1, 'Complete Day'),
                    (2, 'Month End'),
                    (3, 'Complete Month'),
                    (4, 'Fiscal Month End'),
                    (5, 'Entry Order'),
                    (6, 'Entry Order Item'),
                    (7, 'Exit Order'),
                    (8, 'Exit Order Item'),
                    (9, 'Transaction'))
ASSET_FEE_UNITS = ((0, 'Asset Value'),  # total value of the asset
                   (1, 'Asset Qty'),  # how many units of an asset
                   (2, 'NAV Performance'))  # % positive change in the NAV
ASSET_FEE_LEVEL_TYPES = (
    (0, 'Add'),  # Once the next level is reached, the amount form that band is added to lower bands
    (1, 'Replace')  # Once the next level is reached, the value from that level is used for the entire amount
)
SUPER_ASSET_CLASSES = (
    # EQUITY
    ("EQUITY_AU", "EQUITY_AU"),
    ("EQUITY_US", "EQUITY_US"),
    ("EQUITY_EU", "EQUITY_EU"),
    ("EQUITY_EM", "EQUITY_EM"),
    ("EQUITY_INT", "EQUITY_INT"),
    ("EQUITY_UK", "EQUITY_UK"),
    ("EQUITY_JAPAN", "EQUITY_JAPAN"),
    ("EQUITY_AS", "EQUITY_AS"),
    ("EQUITY_CN", "EQUITY_CN"),
    # FIXED_INCOME
    ("FIXED_INCOME_AU", "FIXED_INCOME_AU"),
    ("FIXED_INCOME_US", "FIXED_INCOME_US"),
    ("FIXED_INCOME_EU", "FIXED_INCOME_EU"),
    ("FIXED_INCOME_EM", "FIXED_INCOME_EM"),
    ("FIXED_INCOME_INT", "FIXED_INCOME_INT"),
    ("FIXED_INCOME_UK", "FIXED_INCOME_UK"),
    ("FIXED_INCOME_JAPAN", "FIXED_INCOME_JAPAN"),
    ("FIXED_INCOME_AS", "FIXED_INCOME_AS"),
    ("FIXED_INCOME_CN", "FIXED_INCOME_CN"))
YES_NO = ((False, "No"), (True, "Yes"))
ACCOUNT_TYPE_PERSONAL = 0
ACCOUNT_TYPE_JOINT = 1
ACCOUNT_TYPE_TRUST = 2
ACCOUNT_TYPE_SMSF = 3
ACCOUNT_TYPE_CORPORATE = 4
ACCOUNT_TYPE_401K = 5
ACCOUNT_TYPE_ROTH401K = 6
ACCOUNT_TYPE_IRA = 7  # Traditional pre-tax IRA account
ACCOUNT_TYPE_ROTHIRA = 8  # Tax-paid IRA account
ACCOUNT_TYPE_SEPIRA = 9  # IRA account for self-employed
ACCOUNT_TYPE_403K = 10
ACCOUNT_TYPE_SIMPLEIRA = 11
ACCOUNT_TYPE_SARSEPIRA = 12
ACCOUNT_TYPE_PAYROLLDEDUCTIRA = 13
ACCOUNT_TYPE_PROFITSHARING = 14
ACCOUNT_TYPE_DEFINEDBENEFIT = 15
ACCOUNT_TYPE_MONEYPURCHASE = 16
ACCOUNT_TYPE_ESOP = 17
ACCOUNT_TYPE_GOVERMENTAL = 18
ACCOUNT_TYPE_457 = 19
ACCOUNT_TYPE_409A = 20
ACCOUNT_TYPE_403B = 21
ACCOUNT_TYPE_TRUSTTEST = 22
ACCOUNT_TYPE_TRUSTNONTEST = 23
ACCOUNT_TYPE_INVESTCLUBORGANIZATION = 24
ACCOUNT_TYPE_PARTNERSHIPORGANIZATION = 25
ACCOUNT_TYPE_SOLEPROPORGANIZATION = 26
ACCOUNT_TYPE_LLCORGANIZATION = 27
ACCOUNT_TYPE_ASSOCIATIONORGANIZATION = 28
ACCOUNT_TYPE_NONCORPORATIONORGANIZATION = 29
ACCOUNT_TYPE_PENSION = 30
ACCOUNT_TYPE_HSA = 31
ACCOUNT_TYPE_529 = 32
ACCOUNT_TYPE_ESA = 33
ACCOUNT_TYPE_UG = 34
ACCOUNT_TYPE_GUARDIANSHIP = 35
ACCOUNT_TYPE_CUSTODIAL = 36
ACCOUNT_TYPE_THRIFTSAVING = 37
ACCOUNT_TYPE_OTHER = 99

ACCOUNT_TYPES = (
    (ACCOUNT_TYPE_PERSONAL, "Personal Account"),
    (ACCOUNT_TYPE_JOINT, "Joint Account"),
    (ACCOUNT_TYPE_TRUST, "Trust Account"),
    (ACCOUNT_TYPE_INVESTCLUBORGANIZATION, "Investment Club Account"),
    (ACCOUNT_TYPE_PARTNERSHIPORGANIZATION, "Partnership/Limited partnership Account"),
    (ACCOUNT_TYPE_SOLEPROPORGANIZATION, "Sole Proprietor Account"),
    (ACCOUNT_TYPE_LLCORGANIZATION, "Limited Liability Company Account"),
    (ACCOUNT_TYPE_ASSOCIATIONORGANIZATION, "Association Account"),
    (ACCOUNT_TYPE_NONCORPORATIONORGANIZATION, "Non-corporate organization Account"),
    (ACCOUNT_TYPE_PENSION, "Pension Account"),
    (ACCOUNT_TYPE_401K, "401K Account"),
    (ACCOUNT_TYPE_ROTH401K, "Roth 401K Account"),
    (ACCOUNT_TYPE_IRA, "Individual Retirement Account (IRA)"),
    (ACCOUNT_TYPE_ROTHIRA, "Roth IRA"),
    (ACCOUNT_TYPE_SEPIRA, "SEP IRA"),
    (ACCOUNT_TYPE_403K, "403K Account"),
    (ACCOUNT_TYPE_SIMPLEIRA, "SIMPLE IRA Account (Savings Incentive Match Plans for Employees)"),
    (ACCOUNT_TYPE_SARSEPIRA, "SARSEP Account (Salary Reduction Simplified Employee Pension)"),
    (ACCOUNT_TYPE_PAYROLLDEDUCTIRA, "Payroll Deduction IRA Account"),
    (ACCOUNT_TYPE_PROFITSHARING, "Profit-Sharing Account"),
    (ACCOUNT_TYPE_MONEYPURCHASE, "Money Purchase Account"),
    (ACCOUNT_TYPE_ESOP, "Employee Stock Ownership Account (ESOP)"),
    (ACCOUNT_TYPE_GOVERMENTAL, "Governmental Account"),
    (ACCOUNT_TYPE_457, "457 Account"),
    (ACCOUNT_TYPE_409A, "409A Nonqualified Deferred Compensation Account"),
    (ACCOUNT_TYPE_403B, "403B Account"),
    (ACCOUNT_TYPE_HSA, "Health Savings Account"),
    (ACCOUNT_TYPE_529, "529 college savings plans Account"),
    (ACCOUNT_TYPE_ESA, "Coverdell Educational Savings Account (ESA) Account"),
    (ACCOUNT_TYPE_UG, "UGMA/UTMA Account"),
    (ACCOUNT_TYPE_GUARDIANSHIP, "Guardianship of the Estate Account"),
    (ACCOUNT_TYPE_CUSTODIAL, "Custodial Account"),
    (ACCOUNT_TYPE_THRIFTSAVING, "Thrift Savings Account"),
)
ACCOUNT_TYPES_COUNTRY = {
    'AU': [
        ACCOUNT_TYPE_PERSONAL,
        ACCOUNT_TYPE_JOINT,
        ACCOUNT_TYPE_TRUST,
        ACCOUNT_TYPE_SMSF,
        ACCOUNT_TYPE_CORPORATE,
        ACCOUNT_TYPE_OTHER,
    ],
    'US': [
        ACCOUNT_TYPE_PERSONAL,
        ACCOUNT_TYPE_JOINT,
        ACCOUNT_TYPE_TRUST,
        ACCOUNT_TYPE_SMSF,
        ACCOUNT_TYPE_CORPORATE,
        ACCOUNT_TYPE_401K,
        ACCOUNT_TYPE_ROTH401K,
        ACCOUNT_TYPE_IRA,
        ACCOUNT_TYPE_ROTHIRA,
        ACCOUNT_TYPE_SEPIRA,
        ACCOUNT_TYPE_403K,
        ACCOUNT_TYPE_SIMPLEIRA,
        ACCOUNT_TYPE_SARSEPIRA,
        ACCOUNT_TYPE_PAYROLLDEDUCTIRA,
        ACCOUNT_TYPE_PROFITSHARING,
        ACCOUNT_TYPE_DEFINEDBENEFIT,
        ACCOUNT_TYPE_MONEYPURCHASE,
        ACCOUNT_TYPE_ESOP,
        ACCOUNT_TYPE_GOVERMENTAL,
        ACCOUNT_TYPE_457,
        ACCOUNT_TYPE_409A,
        ACCOUNT_TYPE_403B,
        ACCOUNT_TYPE_OTHER,
        ACCOUNT_TYPE_TRUSTTEST,
        ACCOUNT_TYPE_TRUSTNONTEST,
        ACCOUNT_TYPE_INVESTCLUBORGANIZATION,
        ACCOUNT_TYPE_PARTNERSHIPORGANIZATION,
        ACCOUNT_TYPE_SOLEPROPORGANIZATION,
        ACCOUNT_TYPE_LLCORGANIZATION,
        ACCOUNT_TYPE_ASSOCIATIONORGANIZATION,
        ACCOUNT_TYPE_NONCORPORATIONORGANIZATION,
        ACCOUNT_TYPE_PENSION,
        ACCOUNT_TYPE_SIMPLEIRA,
        ACCOUNT_TYPE_SARSEPIRA,
        ACCOUNT_TYPE_HSA,
        ACCOUNT_TYPE_529,
        ACCOUNT_TYPE_ESA,
        ACCOUNT_TYPE_UG,
        ACCOUNT_TYPE_GUARDIANSHIP,
        ACCOUNT_TYPE_CUSTODIAL,
        ACCOUNT_TYPE_THRIFTSAVING,
    ],
}
US_RETIREMENT_ACCOUNT_TYPES = [
    ACCOUNT_TYPE_401K,
    ACCOUNT_TYPE_ROTH401K,
    ACCOUNT_TYPE_IRA,
    ACCOUNT_TYPE_ROTHIRA,
    ACCOUNT_TYPE_SEPIRA,
]
YAHOO_API = "YAHOO"
GOOGLE_API = "GOOGLE"
API_CHOICES = ((YAHOO_API, "YAHOO"), (GOOGLE_API, 'GOOGLE'))
_asset_fee_ht = "List of level transition points and the new values after that transition. Eg. '0: 0.001, 10000: 0.0'"
PERFORMER_GROUP_STRATEGY = "PERFORMER_GROUP_STRATEGY"
PERFORMER_GROUP_BENCHMARK = "PERFORMER_GROUP_BENCHMARK"
PERFORMER_GROUP_BOND = "PERFORMER_GROUP_BOND"
PERFORMER_GROUP_STOCK = "PERFORMER_GROUP_STOCK"
PERFORMER_GROUP_CHOICE = (
    (PERFORMER_GROUP_STRATEGY, "PERFORMER_GROUP_STRATEGY"),
    (PERFORMER_GROUP_BENCHMARK, "PERFORMER_GROUP_BENCHMARK"),
    (PERFORMER_GROUP_BOND, "PERFORMER_GROUP_BOND"),
    (PERFORMER_GROUP_STOCK, "PERFORMER_GROUP_STOCK")
)
GENDER_MALE = "Male"
GENDER_FEMALE = "Female"
GENDERS = ((GENDER_MALE, "Male"), (GENDER_FEMALE, "Female"))
